### PR TITLE
Feature: SearchBar #5 && Added: My Profile :simple_smile:

### PR DESCRIPTION
**Pull request by pvcodes**
hey, it is been added also, this is not good for long term maybe you can move this site so node.js or flask, that would added more thing + more optimized

### CODE REVIEW

**Comment by pvcodes** [comment]
@yashsehgal I thought u missed the notification!

**Comment by yashsehgal** [comment]
> @yashsehgal I thought u missed the notification!

Extremely sorry for the late response!

**Comment by yashsehgal** [comment]
> hey, it is been added also, 

this is not good for long term maybe you can move this site so node.js or flask, that would added more thing + more optimized

Sure, I will look into the code changes.

**Review by yashsehgal — COMMENTED** [review]
LGTM

**Pull request merged**
